### ISSUE TITLE
Cannot resolve type "c:ContextMenuItem". error when using library inside listview

### ISSUE THREAD

**Issue by Shaboo** [anpin/ContextMenuContainer#3]
You have already mentioned that

![image](https://user-images.githubusercontent.com/5777450/120901408-35b94000-c66d-11eb-94fa-3dc8d1ca4749.png)

but I didn't know how to do it, currently I am having this error when trying to use the ContextMenuContainer inside ListView

`Cannot resolve type "c:ContextMenuItem".`

**Comment by anpin** [comment]
hi, have you added the namespace to your XAML file? You can do it as such 
![image](https://user-images.githubusercontent.com/6060545/120914354-5b564180-c68d-11eb-9a1f-b3d80ea3e15a.png)

**Comment by Shaboo** [comment]
Hi @anpin 

your fast response is very appreciated,

yes indeed I have added the namespace as mentioned by you, please find a minimal project attached to reproduce the issue

thanks again

[App1.zip](https://github.com/anpin/ContextMenuContainer/files/6603965/App1.zip)

**Comment by anpin** [comment]
Hi @Shaboo thanks for your effort. The issue was due to the fact that some code should be called from C# in order for custom XAML namespace to work [as found here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/custom-namespace-schemas).

I pushed the update for that and updated documentation, so in oreder to fix it you need to update the package and call `APES.UI.XF.ContextMenuContainer.Init();` in your `App.xaml.cs`.

I also noticed that the repro wasn't building after the fix cause of how you implemented commands, so I fixed your code too, so you can find it below.
[App1.zip](https://github.com/anpin/ContextMenuContainer/files/6610809/App1.zip)

**Comment by Shaboo** [comment]
@anpin Thank you very much for your quick response, and your fixes for my example

your library is amazing
